#Should firebrands and their projectiles emit light when held or fired?
"Firebrands emit light:" = true
#Should items have additional tooltips when enchanted with certain enchantments?
"Additional enchantment tooltips:" = true
#Should the familiar summoned by Chimes be able to interact with dropped items? This can also be toggled by interacting with the familiar using a Chime.
"Familiar interacts with items:" = true
#Should certain effects from this mod that are meant to support allies affect other players? By default, these effects will try not to support players that you are actively fighting.
"Support effects apply to non-hostile players:" = true
#Should enchantments from this mod be found in villager trades? (Note: This mod adds a lot of item-specific enchantments, so leaving this true might pollute pools with mostly useless enchantments.)
"Artificer's Armory enchantments are tradeable:" = true
#Should Should enchantments from this mod be found on books? (Note: This mod adds a lot of item-specific enchantments, so leaving this true might pollute pools with mostly useless enchantments.)
"Artificer's Armory enchantments are found on books:" = true
#When a player has an active Familiar, should a small HUD appear to the right of their hotbar reflecting the familiar's health and ability readiness?
"Show Familiar HUD:" = true
#Should all necromancy minions appear at half size? This config is mainly to help with visibility.
"Necromancy minions appear at half size:" = false
#What should the default cooldown (in seconds) be for the Firebrand weapon?
#Range: 1 ~ 999
"Firebrand Cooldown:" = 1
#What should the default cooldown (in seconds) be for the Censer weapon?
#Range: 1 ~ 999
"Censer Cooldown:" = 5
#What should the default cooldown (in seconds) be for the Blight weapon?
#Range: 1 ~ 999
"Blight Cooldown:" = 4
#What should the default cooldown (in seconds) be for the Spirit Candle weapon?
#Range: 1 ~ 999
"Spirit Candle Cooldown:" = 3
#What should the default cooldown (in seconds) be for the Chime weapon?
#Range: 1 ~ 999
"Chime Cooldown:" = 1
#What should the default cooldown (in seconds) be for the Wrench weapon?
#Range: 1 ~ 999
"Wrench Cooldown:" = 2
#What should the default cooldown (in seconds) be for the Tuning Fork weapon?
#Range: 1 ~ 999
"Tuning Fork Cooldown:" = 1
#What should the default cooldown (in seconds) be for the Sprig weapon?
#Range: 1 ~ 999
"Sprig Cooldown:" = 3
#What should the default cooldown (in seconds) be for the Oculus weapon?
#Range: 1 ~ 999
"Oculus Cooldown:" = 2
#Should Chime weapons provide a heal when their secondary use to apply a supportive effect is triggered?
"Chimes heal when used outside of summoning a familiar:" = true
#Should censer weapons accept potion effects when used with a potion in the offhand?
"Censers accept potion effects:" = true
#Should Sprigs be able to bonemeal crops?
"Sprigs bonemeal:" = true
#Should certain items should boost certain attributes from Iron's Spells And Spellbooks when held in either hand?
"Boost IS&S Attributes:" = true
#How much of a boost should items from this mod provide to certain Attributes if the above config is enabled?
#Range: 0.01 ~ 1.0
"Percentage Boost:" = 0.15
#Controls whether certain items should boost certain attributes from Ars Nouveau when held in either hand.
"Boost Ars Nouveau Attributes:" = true
#What should the default cooldown (in seconds) be for the Broom weapon?
#Range: 1 ~ 999
"Broom Cooldown:" = 2
#What should the default amount of time (in seconds) be for the duration of the Chime's Blessing effect?
#Range: 1 ~ 999
"Chime Blessing Duration:" = 15

