
["Gameplay Settings"]
	#Should players receive the Unknown Guide Book when they first join the world?
	giveGuideBookOnJoin = false

["Global Spell Scaling"]
	#Global multiplier applied to ALL spells. (1.0 = Default, 0.5 = Half Damage, 2.0 = Double Damage)
	#Range: 0.0 ~ 100.0
	globalDamageMultiplier = 1.0

["Individual Spell Scaling"]
	#Multipliers for specific spells. These stack multiplicatively with the Global multiplier.
	#Damage multiplier for bloodfire column
	#Range: 0.0 ~ 100.0
	bloodfire_column_damage = 1.0
	#Damage multiplier for rhnull impaler
	#Range: 0.0 ~ 100.0
	rhnull_impaler_damage = 1.0
	#Damage multiplier for bloodfire meteor
	#Range: 0.0 ~ 100.0
	bloodfire_meteor_damage = 1.0
	#Damage multiplier for bloodfire soul
	#Range: 0.0 ~ 100.0
	bloodfire_soul_damage = 1.0
	#Damage multiplier for blood scratch
	#Range: 0.0 ~ 100.0
	blood_scratch_damage = 1.0
	#Damage multiplier for blood sphere
	#Range: 0.0 ~ 100.0
	blood_sphere_damage = 1.0
	#Damage multiplier for blood nova
	#Range: 0.0 ~ 100.0
	blood_nova_damage = 1.0
	#Damage multiplier for blood daggersrain
	#Range: 0.0 ~ 100.0
	blood_daggersrain_damage = 1.0
	#Damage multiplier for rhnull heavy sword
	#Range: 0.0 ~ 100.0
	rhnull_heavy_sword_damage = 1.0
	#Damage multiplier for rhnull pain throne
	#Range: 0.0 ~ 100.0
	rhnull_golden_throne_damage = 1.0
	#Damage multiplier for rhnull orb emitter
	#Range: 0.0 ~ 100.0
	rhnull_orb_emitter_damage = 1.0

