version = 3
defaultGlobalExecutorParallelismExpression = "default"
globalExecutorParallelism = "default"

[generalOptimizations]
	midTickChunkTasksInterval = "default"
	optimizeAsyncChunkRequest = "default"

	[generalOptimizations.autoSave]
		mode = "default"
		delay = "default"

[fixes]
	enforceSafeWorldRandomAccess = "default"
	disableLoggingShutdownHook = "default"

[threadedWorldGen]
	enabled = "default"
	allowThreadedFeatures = "default"
	reduceLockRadius = "default"
	asyncScheduling = "default"

[ioSystem]
	replaceImpl = "default"
	async = "default"
	gcFreeChunkSerializer = "default"
	chunkDataCacheSoftLimit = "default"
	chunkDataCacheLimit = "default"
	chunkStreamVersion = "default"

[noTickViewDistance]
	enabled = "default"
	maxConcurrentChunkLoads = "default"
	compatibilityMode = "default"
	ensureChunkCorrectness = "default"

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enabled = "default"
		maxViewDistance = "default"

[vanillaWorldGenOptimizations]
	optimizeAquifer = "default"
	useEndBiomeCache = "default"

