version = 3
defaultGlobalExecutorParallelismExpression = "default"
globalExecutorParallelism = "default"

[generalOptimizations]
	midTickChunkTasksInterval = "default"
	# (Default: true) Whether to let async chunk request no longer block server thread
	# (may cause incompatibility with other mods)
	optimizeAsyncChunkRequest = "default"

	[generalOptimizations.autoSave]
		mode = "default"
		delay = "default"

[fixes]
	# (Default: true) Enforces safe world random access.  
	# This feature detects unsafe off-thread world random access, helping to find the causes  
	# of mysterious "Accessing LegacyRandomSource from multiple threads" crash.  
	# The default behavior is to fail hard when such bad things happens.  
	# Disabling this option will replace this behavior with a warning.  
	# 
	# It is generally not recommended to disable this settings unless you know what you are doing  
	# 
	# 
	enforceSafeWorldRandomAccess = "default"
	disableLoggingShutdownHook = "default"

[threadedWorldGen]
	enabled = "default"
	allowThreadedFeatures = "default"
	reduceLockRadius = "default"
	asyncScheduling = "default"

[ioSystem]
	replaceImpl = "default"
	async = "default"
	gcFreeChunkSerializer = "default"
	# (Default: 8192) Soft limit for io worker nbt cache
	chunkDataCacheSoftLimit = "default"
	# (Default: 32678) Hard limit for io worker nbt cache
	chunkDataCacheLimit = "default"
	# (Default: -1) Defines which chunk compression should be used 
	# -1 for Vanilla default  
	# 1  for GZip (RFC1952) (Vanilla compatible) 
	# 2  for Zlib (RFC1950) (Vanilla default) (Vanilla compatible) 
	# 3  for Uncompressed (Fastest, but higher disk usage) (Vanilla compatible) 
	#  
	# Original chunk data will still readable after modifying this option  
	# as this option only affects newly stored chunks 
	# Invalid values will fall back to vanilla default
	# 
	chunkStreamVersion = "default"

[noTickViewDistance]
	enabled = "default"
	maxConcurrentChunkLoads = "default"
	compatibilityMode = "default"
	ensureChunkCorrectness = "default"

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		maxViewDistance = "default"
		# (Default: true) Whether to modify maximum view distance
		enabled = "default"

[vanillaWorldGenOptimizations]
	# (Default: true) Whether to enable aquifer optimizations to accelerate overworld worldgen
	# (may cause incompatibility with other mods)
	optimizeAquifer = "default"
	# (Default: true) Whether to enable End Biome Cache to accelerate The End worldgen 
	# This is no longer included in lithium-fabric 
	# (may cause incompatibility with other mods)
	# 
	useEndBiomeCache = "default"

