#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 26 21:37:57 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.2.zip
enableShaders=true
