#Updated by ShaderCycler
#Sun Jun 14 23:06:53 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.1.zip
enableShaders=false
