#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 20 17:28:47 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.1.zip
enableShaders=false
