
[General]
	#Cycle mode: 'loop', 'reverse', or 'random'
	cycleMode = "random"
	#Delay in milliseconds before shader reload
	#Range: 0 ~ 10000
	reloadDelay = 197
	#Enable sound feedback when switching shaders
	enableSounds = true
	#Enable chat notifications when shaders are switched
	enableChatNotifications = false

[Exclusions]
	#List of shader pack filenames to exclude from cycling (case-sensitive, e.g., 'wavy-shader.zip')
	excludedShaders = ["None"]

[DimensionShaderSwitch]
	#Enable dimension-specific shader override for Overworld
	enableOverworldOverride = false
	#Enable dimension-specific shader override for Nether
	enableNetherOverride = false
	#Enable dimension-specific shader override for The End
	enableEndOverride = false
	#Shader to apply automatically when entering the Overworld. Use 'None' to disable.
	overworldShader = "Mellow Shader v1.5.5a.zip"
	#Shader to apply automatically when entering the Nether. Use 'None' to disable.
	netherShader = "Mellow Shader v1.5.5a.zip"
	#Shader to apply automatically when entering The End. Use 'None' to disable.
	endShader = "Mellow Shader v1.5.5a.zip"
	#List of dimension=shader mappings. Example: minecraft:overworld=None
	#Use 'None' to indicate no shader for that dimension.
	dimensionShaderList = ["bloodmagic:dungeon=Mellow Shader v3.1.zip", "bloodyhell:soul_dimension=Disable Shaders", "perdition:dis=Mellow Shader v3.1.zip", "minecraft:overworld=None", "blood_arsenal_reawakened:white_day=None", "mahoutsukai:reality_marble=None", "fracture:flesh_dimension=None", "reverseeon:island_dim=None", "thedulling:heart_of_the_dulling=None", "perdition:purgatory=None", "minecraft:the_end=None", "minecraft:the_nether=None", "spectrum:deeper_down=None", "fracture:boreas_dimension=None", "thedulling:yvxzlight=None", "thedulling:lost_interfold=None", "blood_arsenal_reawakened:black_void=None"]

