block_respawn_point_set_message = true

#Triggers
[triggers]
	#Banner for lighting up campfires
	campfire_lit = true
	entity_felled = true
	raid_status = true
	entity_spawned = true
	player_spawned = true
	player_felled = true
	player_spawn_set = true

	#Compatibility
	[triggers.compatibility]
		#Banner for activating bonfires [Bonfires Mod]
		bonfires_bonfire_lit = true
		#Banner for activating waystones [Waystones Mod]
		waystone_activated = true
		#Banner for retrieving experience catalyst [Irons RPG Tweaks]
		xp_catalyst_retrieved = true

