
#Triggers
[triggers]
	#Banner for lighting up campfires
	campfire_lit = true
	entity_felled = true
	raid_status = true
	entity_spawned = true
	player_spawned = true
	player_felled = true
	player_spawn_set = true

	#Compatibility
	[triggers.compatibility]
		#Banner for activating bonfires [Bonfires Mod]
		bonfire_lit = true
		#Banner for activating waystones [Waystones Mod]
		waystones_activate = true

